version: "3.9"
services:
    footstep_planner:
        image: "run_footstep_planner"
        volumes:
            - ${XAUTHORITY}:/tmp/.XAuthority
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            XAUTHORITY: "/tmp/.XAuthority"
            DISPLAY: "${DISPLAY}"
        stdin_open: true
        tty: true
